/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IDuoPhone: typeof import('~icons/duo/phone')['default']
    IMonoArrowUp: typeof import('~icons/mono/arrow-up')['default']
    IMonoInstagram: typeof import('~icons/mono/instagram')['default']
    IMonoPlay: typeof import('~icons/mono/play')['default']
    IMonoTelegram: typeof import('~icons/mono/telegram')['default']
    IMonoWhatsapp: typeof import('~icons/mono/whatsapp')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
